name: 3A5000
on:
  push:
  workflow_dispatch:

jobs:
  os-release:
    runs-on: self-hosted
    steps:
      - name: Show OS release info
        run: cat /etc/os-release

  checkout-v7-0-1:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
