name: 3A5000
on:
  push:
  workflow_dispatch:

jobs:
  os-release:
    runs-on: self-hosted
    steps:
      - name: Show OS release info
        run: cat /etc/os-release

  checkout-v3:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

  checkout-v4:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

  checkout-v5:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

  checkout-v6:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

  checkout-v7:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
